---
- name: Restart wireguard
  ansible.builtin.systemd_service:
    name: "wg-quick@{{ qbittorrent_wg_interface }}"
    state: restarted
    daemon_reload: true

- name: Reload the kill switch
  ansible.builtin.systemd_service:
    name: qbittorrent-killswitch
    state: restarted
    daemon_reload: true

- name: Restart vpn-health
  ansible.builtin.systemd_service:
    name: vpn-health
    state: restarted
    daemon_reload: true

- name: Restart qbittorrent
  ansible.builtin.systemd_service:
    name: qbittorrent
    state: restarted
    daemon_reload: true
